version: '3.4'

services:
  postgres:
    container_name: my_notes_db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: my_notes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0902
    ports:
      - "5176:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
