# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  mynotes:
    image: mynotes
    build:
      context: .
      dockerfile: MyNotes/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5176:5176
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
